# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.0
maven_group = com.gaura.twod_projectiles
archives_name = twod_projectiles
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.5

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.128.1+1.21.5
neoforge_version = 21.5.66-beta
cloth_config_version = 18.0.145
mod_menu_version = 14.0.0-rc.2
