modLoader = "javafml"
loaderVersion = "[2,)"
modURL = "https://modrinth.com/mod/twod_projectiles"
issueTrackerURL = "https://github.com/Gauraaaaaaaa/TwoDProjectiles/issues"
license = "ARR"

[[mods]]
modId = "twod_projectiles"
version = "${version}"
displayName = "2D Projectiles"
authors = "Gaura"
description = '''Makes projectiles (arrows, firework rockets, etc.) look like the Minecraft trailers!'''
logoFile = "assets/twod_projectiles/icon.png"

[[dependencies.twod_projectiles]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.twod_projectiles]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "twod_projectiles.mixins.json"
