modLoader = "javafml"
loaderVersion = "[4,)"
modURL = "https://modrinth.com/mod/twod_projectiles"
issueTrackerURL = "https://github.com/Gauraaaaaaaa/TwoDProjectiles/issues"
license = "ARR"

[[mods]]
modId = "twod_projectiles"
version = "${version}"
displayName = "2D Projectiles"
authors = "Gaura"
description = '''Makes projectiles (arrows, firework rockets, trident, etc.) look 2D!'''
logoFile = "assets/twod_projectiles/icon.png"

[[dependencies.twod_projectiles]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.twod_projectiles]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "twod_projectiles.mixins.json"
